# Generated by Django 5.1.8 on 2026-06-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='event_type',
            field=models.CharField(choices=[('enter', 'Entrada'), ('exit', 'Salida')], default='enter', max_length=10),
        ),
    ]
